/// <reference types="react" />
import { CandlestickChart as _CandlestickChart } from './Chart';
import { CandlestickChartCandles } from './Candles';
import { CandlestickChartCrosshair } from './Crosshair';
import { CandlestickChartProvider } from './Context';
import { CandlestickChartPriceText } from './PriceText';
import { CandlestickChartDatetimeText } from './DatetimeText';
import { CandlestickChartCrosshairTooltip } from './CrosshairTooltip';
import { useCandlestickChartDatetime } from './useDatetime';
import { useCandlestickChartPrice } from './usePrice';
import { useCandlestickChart } from './useCandlestickChart';
import { useCandleData } from './useCandleData';
export * from './Chart';
export * from './Candle';
export * from './Candles';
export * from './Context';
export * from './Crosshair';
export * from './PriceText';
export * from './DatetimeText';
export * from './Line';
export * from './CrosshairTooltip';
export * from './types';
export * from './useCandlestickChart';
export * from './useDatetime';
export * from './usePrice';
export * from './useCandleData';
export * from './utils';
export declare const CandlestickChart: typeof _CandlestickChart & {
    Candle: ({ candle, maxHeight, domain, margin, positiveColor, negativeColor, rectProps: overrideRectProps, lineProps: overrideLineProps, index, width, useAnimations, renderLine, renderRect, }: import("./Candle").CandlestickChartCandleProps) => JSX.Element;
    Candles: typeof CandlestickChartCandles;
    Crosshair: typeof CandlestickChartCrosshair;
    Provider: typeof CandlestickChartProvider;
    PriceText: typeof CandlestickChartPriceText;
    DatetimeText: typeof CandlestickChartDatetimeText;
    Line: ({ color, x, y, ...props }: import("./Line").CandlestickChartLineProps) => JSX.Element;
    Tooltip: typeof CandlestickChartCrosshairTooltip;
    useDatetime: typeof useCandlestickChartDatetime;
    usePrice: typeof useCandlestickChartPrice;
    useChart: typeof useCandlestickChart;
    useCandleData: typeof useCandleData;
};
