/// <reference types="react" />
import { LineChart as _LineChart } from './Chart';
import { LineChartPathWrapper } from './ChartPath';
import { LineChartHighlight } from './Highlight';
import { LineChartProvider } from './Context';
import { LineChartCursor } from './Cursor';
import { LineChartCursorCrosshair } from './CursorCrosshair';
import { LineChartCursorTrustee } from './CursorTrustee';
import { LineChartCursorLine } from './CursorLine';
import { LineChartDot } from './Dot';
import { LineChartGradient } from './Gradient';
import { LineChartGroup } from './Group';
import { LineChartHorizontalLine } from './HorizontalLine';
import { LineChartTooltip } from './Tooltip';
import { LineChartPriceText } from './PriceText';
import { LineChartDatetimeText } from './DatetimeText';
import { useLineChartDatetime } from './useDatetime';
import { useLineChartPrice } from './usePrice';
import { useLineChart } from './useLineChart';
export * from './Chart';
export * from './ChartPath';
export * from './Highlight';
export * from './Context';
export * from './Cursor';
export * from './CursorCrosshair';
export * from './CursorTrustee';
export * from './CursorLine';
export * from './Dot';
export * from './Gradient';
export * from './Tooltip';
export * from './DatetimeText';
export * from './Path';
export * from './PriceText';
export * from './useDatetime';
export * from './useLineChart';
export * from './usePrice';
export * from './types';
export declare const LineChart: typeof _LineChart & {
    Chart: typeof _LineChart;
    Dot: typeof LineChartDot;
    Path: typeof LineChartPathWrapper;
    Cursor: typeof LineChartCursor;
    CursorCrosshair: typeof LineChartCursorCrosshair;
    CursorTrustee: typeof LineChartCursorTrustee;
    CursorLine: typeof LineChartCursorLine;
    Gradient: typeof LineChartGradient;
    Group: typeof LineChartGroup;
    Highlight: typeof LineChartHighlight;
    HorizontalLine: typeof LineChartHorizontalLine;
    Tooltip: typeof LineChartTooltip;
    Provider: typeof LineChartProvider;
    PriceText: typeof LineChartPriceText;
    DatetimeText: typeof LineChartDatetimeText;
    useDatetime: typeof useLineChartDatetime;
    usePrice: typeof useLineChartPrice;
    useChart: typeof useLineChart;
    HoverTrap: () => JSX.Element;
};
